const Subject = [
  { name: "English Language", year: 2022, totalQuestions: 40 },
  { name: "Mathematics", year: 2021, totalQuestions: 40 },
  { name: "Chemistry", year: 2022, totalQuestions: 40 },
  { name: "Physics", year: 2022, totalQuestions: 40 },
  { name: "Biology", year: 2022, totalQuestions: 40 },
  { name: "Literature In English", year: 2022, totalQuestions: 40 },
  { name: "Government", year: 2022, totalQuestions: 40 },
  { name: "Economics", year: 2022, totalQuestions: 40 },
  { name: "Commerce", year: 2022, totalQuestions: 40 },
  { name: "Financial Accounting", year: 2022, totalQuestions: 40 },
  { name: "Computer Science", year: 2022, totalQuestions: 40 },
  { name: "Physical Education", year: 2022, totalQuestions: 40 },
  { name: "Sociology", year: 2022, totalQuestions: 40 },
  { name: "Political Science", year: 2022, totalQuestions: 40 },
  { name: "Anthropology", year: 2022, totalQuestions: 40 },
  { name: "Philosophy", year: 2022, totalQuestions: 40 },
  { name: "Engineering", year: 2022, totalQuestions: 40 },
  { name: "Medicine", year: 2022, totalQuestions: 40 },
  { name: "Law", year: 2022, totalQuestions: 40 },
  { name: "Languages", year: 2022, totalQuestions: 40 },
  { name: "Drama", year: 2022, totalQuestions: 40 },
  { name: "Environmental Science", year: 2022, totalQuestions: 40 },
  { name: "Culinary Arts", year: 2022, totalQuestions: 40 },
  { name: "Business", year: 2022, totalQuestions: 40 },
  { name: "Marketing", year: 2022, totalQuestions: 40 },
  { name: "Architecture", year: 2022, totalQuestions: 40 },
  { name: "Fashion Design", year: 2022, totalQuestions: 40 },
  { name: "Art History", year: 2022, totalQuestions: 40 },
  { name: "Psychology", year: 2022, totalQuestions: 40 },
  { name: "Music Theory", year: 2022, totalQuestions: 40 },
  { name: "Geology", year: 2022, totalQuestions: 40 },
  { name: "Film Studies", year: 2022, totalQuestions: 40 },
  { name: "Astronomy", year: 2022, totalQuestions: 40 },
  { name: "Physical Therapy", year: 2022, totalQuestions: 40 },
  { name: "Fashion Merchandising", year: 2022, totalQuestions: 40 },
  { name: "Graphic Design", year: 2022, totalQuestions: 40 },
  { name: "Nutrition", year: 2022, totalQuestions: 40 },
  { name: "Civil Engineering", year: 2022, totalQuestions: 40 },
  { name: "Christian Religious Studies", year: 2022, totalQuestions: 40 },
  { name: "Islamic Religious Studies Engineering", year: 2022, totalQuestions: 40 },
  // A
  // Add more subjects here
];

export default Subject;
