export const examSubjectsArr = [
    {
        subject: "English Language",
        alias: "Engl",
        id: 1,
        classes: {
            "Lexis and Structure": [
				{ topic: "Synonyms", subTopics: ["Words that are similar in meaning"] },
				{ topic: "Antonyms", subTopics: ["Words that are opposite in meaning"] },
				{ topic: "Homonyms", subTopics: ["Word that both sounds and is spelled the same"] },
				{ topic: "Spelling and Punctuation", subTopics: ["Spelling bee and Punctuation marker"] },
				{ topic: "Figure of speech", subTopics: ["Literary Manner of speaking", "Simile/Metaphor/Hyperbole"] },
				{ topic: "Idiomatic expression", subTopics: ["Words or phrase that departs from straightforward, literal language."] },
				{ topic: "Question tags", subTopics: ["Question tags", "Reported speech"] },
				{ topic: "Concord", subTopics: ["Concord questions"] },
				{ topic: "Clauses/Phrase and sentence pattern", subTopics: ["Phrase and Clauses"] },
				{ topic: "Word classes and their functions", subTopics: ["Word class"] },
				{ topic: "Comparative and Superlative", subTopics: ["Comparative"] },
			],
			"Oral Forms": [
				{ topic: "Vowel sound", subTopics: ["monothongs", "diphthongs"] },
				{ topic: "Consonant sound", subTopics: ["Clusters", "Selected consonant sounds"] },
				{ topic: "Rhymes", subTopics: ["Homophone"] },
				{ topic: "Word stress", subTopics: ["monosyllabic and polysyllabic"] },
				{ topic: "Intonation", subTopics: ["words and emphatic stress"] },
			],
			"Comprehension and Summary": [
				{ topic: "Descriptive", subTopics: ["Descriptive comprehension passages"] },
				{ topic: "Narrative", subTopics: ["Narrative comprehension passages"] },
				{ topic: "Expository", subTopics: ["Expository comprehension passages"] },
				{ topic: "Argumentative/Persuasive", subTopics: ["Argumentative comprehension passages"] },
			],
			
        },
    },
    {
        subject: "Mathematics",
        alias: "Maths",
        id: 2,
        classes: {
            ss1: [
				{ topic: "Number base system", subTopics: ["Binary/Ocal system"] },
				{ topic: "Modular arithmetic", subTopics: ["Modulo/Calendar"] },
				{ topic: "Fraction • Standard form • indices", subTopics: ["Fraction and BODMAS", "Index and standard form"] },
				{ topic: "Sets", subTopics: ["Set and set Notation", "Venn diagram"] },
				{ topic: "Change of subject formula", subTopics: ["Make a term the subject of formula"] },
				{ topic: "Variation and proportion", subTopics: ["Direct/indirect variation"] },
				{ topic: "Geometric construction", subTopics: ["WAEC and NECO construction questions"] },
				{ topic: "Polygon and congruent triangle", subTopics: ["Sum of angles in a polygon"] },
				{ topic: "Speed/Velocity", subTopics: ["Questions on speed"] },
				{ topic: "Plane/Solid mensuration", subTopics: ["Sector and segment/Length of arc", "Frustum of Cone and pyramid", "Cylinder"] },
			],
			ss2: [
				{ topic: "Logarithm", subTopics: ["Logarithmic equation"] },
				{ topic: "Approximation", subTopics: ["approximation and percentage error", "Rounding off and significant figures"] },
				{ topic: "AP/GP • Sequence and series", subTopics: ["Arithmetic and Geometric Progression - AP and GP"] },
				{ topic: "Quadratic equations", subTopics: ["Make quadratic equation a perfect square", "Root of quadratic equations"] },
				{ topic: "Simultaneous equation", subTopics: ["Solving simultaneous equations"] },
				{ topic: "Gradient of curves and lines", subTopics: ["Gradient/Gradient Equations"] },
				{ topic: "Logical reasonings", subTopics: ["Truth table"] },
				{ topic: "Linear inequalities", subTopics: ["Linear inequalities in one and two variables"] },
				{ topic: "Algebraic fractions", subTopics: ["Algebra and equations"] },
				{ topic: "Geometry", subTopics: ["Chords and arcs/alternate angles"] },
				{ topic: "Circle Theorems", subTopics: ["Cyclic quadrilaterals and circle Theorems"] },
				{ topic: "Trigonometry/Trigonometric ratios", subTopics: [" Sine and Cosine rule", "Quadrant - ASTC"] },
				{ topic: "Bearing and distance", subTopics: ["Elements of bearing and calculations"] },
				{ topic: "Angles of elevation and depression", subTopics: ["Calculations"] },
				{ topic: "Measures of central tendency  (Group and Ungrouped data)", subTopics: ["Measures of central tendency  (Group and Ungrouped data)", "Arithmetic and Geometric mean of data", "Mean/Median and Mode", "Pie chart/Bar chart"] },
				{ topic: "Measures of Dispersion", subTopics: ["Mean/Standard deviation and variance", "Quartile range"] },
				{ topic: "Histogram and cumulative frequency", subTopics: ["O-give", "Frequency polygon"] },
				{ topic: "Probability", subTopics: ["Probability questions"] },
				
			],
			ss3: [
				{ topic: "Surds", subTopics: ["Surd and Surdic equation"] },
				{ topic: "Matrices and determinants", subTopics: ["Matrices and inverse"] },
				{ topic: "Percentage Profit and Loss", subTopics: ["Arithmetic mathematics"] },
				{ topic: "Latitude and longitude", subTopics: ["Questions on parallel of latitude and longitude"] },
				{ topic: "Geometry of Straight line", subTopics: ["Gradient and midpoint of a line", "Distance between two points", "Parallelism and Perpendicularity"] },
				{ topic: "Differentiation", subTopics: ["Differential calculus"] },
				{ topic: "Integration", subTopics: ["Integral Calculus"] },
			],
        },
    },
    {
        subject: "Chemistry",
        alias: "Chem",
        id: 3,
        classes: {
            ss1: [
				{ topic: "Introduction to Chemistry", subTopics: ["Scientific method", "Careers in Chemistry"] },
				{ topic: "Nature of matter", subTopics: ["Separation Techniques", "Purity", "Physical and chemical changes"] },
				{ topic: "Particulate nature of matter", subTopics: ["Atoms, Molecules and ions", "Laws of chemical combination", "Valency", "Relative atomic/molecular mass" ] },
				{ topic: "Atomic Structure • Chemical Combinations", subTopics: ["Electronic configuration", "Electrovalent/covalent bond", "Dalton's atomic theory", "Bohr's and Thompson's atomic model"] },
				{ topic: "Gas laws • Kinetic Theory of Matter", subTopics: ["Limitations of the Kinetic theory of matter", "Relative vapour density", "Boyle's/Charles/Gay Lussacs/Avogadro's/Ideal gas law", "Dalton's law of partial pressure/Graham's law", ] },
				{ topic: "Acids • Bases • Salts", subTopics: ["Acidity and alkalinity", "PH scale", "PH/POH", "Water of crystallisation/Efflorescence/Effervescence/Deliquescence/Hygroscopy"] },
				{ topic: "Carbon and its compound", subTopics: ["Allotropy", "Graphite/Diamond/Coke/Coal/Charcoal", "Carbon cycle"] },
				{ topic: "Empirical/Molecular formula", subTopics: ["calculations"] },
				{ topic: "Hydrocarbons", subTopics: ["Petroleum/Cracking", "Catalytic reforming", "Octane rating"] },
				{ topic: "Water • Solution • Solubility", subTopics: ["Natural and treated water", "Hardness of water", "Colloids/Suspension/Saturated solution"] },
			],
			ss2: [
				{ topic: "Volumetric and qualitative analysis", subTopics: ["Stoichiometry - Mass and Volume relationship", "Titration/Molarity/Solubility"] },
				{ topic: "Periodic table", subTopics: ["Periodicity", "Metals/Non metals/Metalloids", "Lanthanide/Actinide/Transition elements", "Atomic/Ionic size • Atomic radius", "Electronegativity/Ionisation energy/Electron affinity"] },
				{ topic: "Types of reactions • Oxidation and Reduction", subTopics: ["Redox Reaction", "Oxidising and reducing agent", "Catalyst"] },
				{ topic: "Electrolysis", subTopics: ["Electrode Potential", "Ionic theory/Purification of metals", "Faraday's laws and Electrochemical cells", "Extraction and Purification of metals/Electroplating/Electrolysis of brine"] },
				{ topic: "Energy and chemical reactions", subTopics: ["Exothermic and endothermic reactions", "Gibbs Free energy/Enthalpy and entropy/Spontaneous reaction"] },
				{ topic: "Rates of reaction", subTopics: ["Collision theory", "Activation energy", "Energy barrier"] },
				{ topic: "Chemical Equilibrium", subTopics: ["Le Chateliers principles", "Reversible reactions", "Contact process/Haber process"] },
				{ topic: "Air • Air Pollution", subTopics: ["Types of Flames/Photosynthetic reactions", "Chlorofluorocarbons/Green House effect", "Ozone layer"] },
				{ topic: "Shapes of Molecules", subTopics: ["Shapes of Substances", "Dipole Dipole attraction", "Crystalline/Amorphous"] },
				{ topic: "Radioactivity • Nuclear Chemistry", subTopics: ["Nuclear reactions", "Alpha, Beta and Gamma rays", "Transmutation of atoms", "Nuclear Fission/Fusion"] },
				{ topic: "Halogens • Chlorine and its compound", subTopics: ["Fluorine/Bromine/Iodine", "Halogens • Chlorine and its compound"] },
				{ topic: "Oxygen and its compound", subTopics: ["Hydrogen peroxide/Ozone", "Amphoteric/Neutral Oxides and Peroxides"] },
				{ topic: "Hydrogen and its compound", subTopics: ["Hydrogen/Hydrides"] },
				{ topic: "Sulphur and its compound", subTopics: ["Sulphides", "Plastic/Rhombic/Monoclinic sulphur"] },
				{ topic: "Nitrogen and its compound", subTopics: ["Ammonia"] },
				{ topic: "Metals and its compound", subTopics: ["Extraction of metals", "Alloys/Duralumin/Alnico"] },
				{ topic: "Organic Chemistry (1)", subTopics: ["Stereochemistry/Isomerism", "Alkane/Alkene/Alkyne/Alkanol/Benzene"] },
			],
			ss3: [
				{ topic: "Phosphorus and its compound", subTopics: ["Phosphine and Phosphorus"] },
				{ topic: "Silicon and its compound", subTopics: ["Silicate and Sand"] },
				{ topic: "Organic Chemistry (2)", subTopics: ["Detergent/Fat and oil(Saponification)", "Rubber/Polymer", "Alkanone/Alkanal/Alkanoic acid", "Amino/Carbohydrates/Amine/Amide"] },
				{ topic: "Industrial Chemistry", subTopics: ["Heavy/Fine chemical industries"] },
				{ topic: "Chemistry of Earth and space", subTopics: ["Stars/Moons/Space travel", "Asteroids/Comets/Meteoroids"] },
			],
        },
    },
    {
        subject: "Physics",
        alias: "Phy",
        id: 4,
        classes: {
            ss1: [
				{ topic: "Units and measurement", subTopics: ["Fundamental/Derived Quantity and unit", "Dimensional analysis", "Mass vs Weight"] },
				{ topic: "Motion • Friction", subTopics: ["Types of motion", "Circular and Brownian motion", "Method of reducing friction", "Coefficient of friction"] },
				{ topic: "Velocity Time graph", subTopics: ["Position/Distance and displacement", "graph of motion"] },
				{ topic: "Work • Energy and Power", subTopics: ["Conservation of mechanical energy"] },
				{ topic: "Heat energy (1)", subTopics: ["Transfer of heat", "Linear/Area/Cubic expansivity"] },
				{ topic: "Electric charges (1)", subTopics: ["Gold leaf electroscope", "Electrophorus", "Point charges/Ways of distribution of charges"] },
				{ topic: "Description and properties of field", subTopics: ["basic concept of gravitational field/Electric Field", "Magnetism"] },
				{ topic: "Electric Field (1)", subTopics: ["Electric lines of force", "P.D and E.M.F", "Electric circuit and Ohms law", "Series and parallel resistors"] },
				{ topic: "Particle nature of matter", subTopics: ["Kinetic theory and state of matter", "Atoms/Molecules/Ions/Electron/Proton/Neutron"] },
				{ topic: "Crystal structure", subTopics: ["Crystalline and non crystalline"] },
				{ topic: "Elasticity of solid", subTopics: ["Hooke's law", "Young's modulus"] },
				{ topic: "Fluid at rest and in motion", subTopics: ["Surface tension", "Capillarity and Viscosity", "Terminal velocity"] },
				{ topic: "Harvesting of solar energy", subTopics: ["Solar energy production/Solar cells and panels"] },
			],
			ss2: [
				{ topic: "Scalars and vector quantity", subTopics: ["Addition and resolution of vector", "Parallelogram law and triangular laws of vector"] },
				{ topic: "Motion (2)", subTopics: ["Equations of motion"] },
				{ topic: "Projectiles", subTopics: ["Projectile motion", "Time of flight/Maximum height and Range"] },
				{ topic: "Equilibrium of forces in Solid", subTopics: ["Moment of force", "Center of gravity", "stability"] },
				{ topic: "Equilibrium of forces in Liquid", subTopics: ["Archimedes Principle", "Floatation", "Density and relative density/Hydrometer"] },
				{ topic: "Simple Harmonic Motion (SHM)", subTopics: ["Forced vibration and resonance", "Frequency and Period of a vibrating body"] },
				{ topic: "Linear Momentum", subTopics: ["Impulse and Momentum/Inertia", "Newton's laws of motion", "Elastic/Inelastic collision"] },
				{ topic: "Mechanical Energy • Machines", subTopics: ["Mechanical Advantage/Velocity ratio of a machine", "Lever system"] },
				{ topic: "Heat Energy (2)", subTopics: ["Thermometer/Thermometric substances and scales", "Specific heat capacity and latent heat", "Relative humidity and few point"] },
				{ topic: "Gas laws", subTopics: ["Gas pressure", "Boyle's/Charles/Pressure law and kinteic theory of gases"] },
				{ topic: "Waves", subTopics: ["Mechanical/Electromagnetic wave", "Progressive wave/Node and antinode"] },
				{ topic: "Reflection of light wave", subTopics: ["Rectilinear propagation of light", "Transparent/Opaque/Sources of light", "Mirror equation"] },
				{ topic: "Refraction of light", subTopics: ["Total internal reflection/Critical angle", "Refraction", "Dispersion of light", "Color addition"] },
				{ topic: "Application of light wave", subTopics: ["Camera vs Human eye", "Microscope and telescope"] },
				{ topic: "Sound wave", subTopics: ["Hearing aids", "Characteristics of sound- Loudness/Pitch/Frequency", "Vibration in strings and pipes"] },
				{ topic: "Pressure in fluids", subTopics: ["Pascal's principle/Concept of pressure"] },
			],
			ss3: [
				{ topic: "Electromagnetic wave", subTopics: ["Uses of electromagnetic wave", "Types of radiation"] },
				{ topic: "Gravitational field", subTopics: ["Newton's universal law of gravitation", "Escape velocity/Kepler's laws of planetary motion", "Natural/Artificial Satellite"] },
				{ topic: "Coulomb's law • Electric Field (2)", subTopics: ["Capacitor and capacitance", "electric field intensity"] },
				{ topic: "Current electricity • Electric Field (3)", subTopics: ["Internal resistance of a cell", "Resistivity and conductivity", "Galvanometer/Voltmeter/Ammeter conversion"] },
				{ topic: "Electrolysis", subTopics: ["Electrolysis and Faraday's laws", "Thermionic emission/Hot cathode ray"] },
				{ topic: "Magnetic Field", subTopics: ["Method of making magnet", "Permanent and Non permanent magnet", "Earth's magnetic field"] },
				{ topic: "Electromagnetic Field", subTopics: ["Faraday's laws of electromagnetic induction/Eddy current", "Transformer/Power transmission/Induction coil"] },
				{ topic: "Simple A.C circuits", subTopics: ["RLC circuit/Capacitance and Impedance"] },
				{ topic: "Atomic models", subTopics: ["Atoms"] },
				{ topic: "Radioactivity • Nuclear Physics", subTopics: ["Alpha, Beta and Gamma rays", "Transmutation of atoms", "Nuclear Fission/Fusion"] },
				{ topic: "Energy Quantisation", subTopics: ["Franck Hertz experiment", "Atomic spectra and photoelectric effect/Xrays"] },
				{ topic: "Wave particle duality", subTopics: ["Uncertainty principle", "complementary variables", "Wave and particulate nature of matter"] },
				{ topic: "Semiconductor • Basic electronics", subTopics: ["semi conductors/Diode/Triode/Electrons and holes", "P-N junction diode"] },
				{ topic: "Rocket • Satellite", subTopics: ["Rocket science", "Nigeria Sat - 1", "NigCom-sat-1"] },
				{ topic: "Energy and society", subTopics: ["Renewable energy", "Energy crisis"] },
			],
        },
    },
    {
        subject: "Biology",
        alias: "Bio",
        id: 5,
        classes: {
            ss1: [
				{ topic: "Recognising living things", subTopics: ["Biology and living things", "Characteristics of living things", "Organisation of life", "Complexity of organisation in higher organisms"] },
				{ topic: "Classification of living things", subTopics: ["Kingdom Monera/Protista/Fungi/Plantae/Animalia"] },
				{ topic: "The Cell", subTopics: ["Plant cell vs Animal cell"] },
				{ topic: "The cell and its environment", subTopics: ["Diffusion/Osmosis", "Plasmolysis/Haemolysis", "Turgidity/Faccidity"] },
				{ topic: "Cell • Properties and functions", subTopics: ["Excretion/Growth", "Nutrition/Cellular respiration", "Reaction of cell to its environment/Movement/Reproduction"] },
				{ topic: "Plant nutrition", subTopics: ["Photosynthesis/Mineral resources of plants"] },
				{ topic: "Animal nutrition", subTopics: ["Dentition/Digestive enzyme", "Food test and balance diet", "Food/Mode of nutrition/Holozoic organisms"] },
				{ topic: "Tissues and supporting systems", subTopics: ["Skeleton", "Supporting tissues in plant/animals"] },
				{ topic: "Basic ecological concepts", subTopics: ["Ecology/Biotic factors/Biomass", "Ecological factors/Population studies", "Soil"] },
				{ topic: "Functioning ecosystem", subTopics: ["Pyramid of Energy/Numbers", "Food chain/web and trophic level", "Autotrophs vs Heterotroph"] },
				{ topic: "Energy transformation in nature", subTopics: ["Laws of thermodynamics and flow of energy"] },
				{ topic: "Relevance of Biology to Agriculture", subTopics: ["Population growth and food supply", "Pests and diseases", "Food production and storage"] },
				{ topic: "Micro organisms", subTopics: ["micro organisms around us"] },
				{ topic: "Aquatic habitat", subTopics: ["Marine habitat", "Estuarine/Fresh water habitat"] },
				{ topic: "Terrestrial habitat", subTopics: ["Marshy and Forest habitat", "Grassland/Arid habitat"] },
				{ topic: "Reproduction in unicellular organisms and invertebrates", subTopics: ["Reproduction in Amoeba/Paramecium/Spirogyra/Earthworm/Cockroach/Housefly/Snail/Toad", "Metamorphosis in insects"] },
				
			],
			ss2: [
				{ topic: "Classification of plants", subTopics: ["Life cycle of plants and agricultural/botanical classification"] },
				{ topic: "Digestive system", subTopics: ["Alimentary tract/Feeding habitat", "Feeding in protozoa/hydra/mammal"] },
				{ topic: "Transport system", subTopics: ["circulatory system", "Diffusion and osmosis"] },
				{ topic: "Respiratory system", subTopics: ["Respiration vs photosynthesis"] },
				{ topic: "Excretory system", subTopics: ["Excretion in mammals and plants"] },
				{ topic: "Nutrient cycle", subTopics: ["Carbon/oxygen/water/Nitrogen cycle"] },
				{ topic: "Ecological management", subTopics: ["biological association/Tolerance/adaptation and pollution"] },
				{ topic: "Conservation of natural resources", subTopics: ["Natural resources"] },
				{ topic: "Pests and Crop disease", subTopics: ["Crop pests"] },
				{ topic: "Reproductive system in vertebrates", subTopics: ["Reproduction in Fish/Reptiles/Birds/Mammals"] },
				{ topic: "Reproductive system in plants • plant pollination", subTopics: ["Reproductive system in plants and plant pollination", "Flowers and agents of pollination"] },
				{ topic: "Pollution", subTopics: ["Atmospheric pollution"] },
			],
			ss3: [
				{ topic: "Hormone • Regulation of internal environment", subTopics: ["Homeostasis and osmoregulation", "Kidney/liver/skin", "Plant and animal hormone"] },
				{ topic: "Nervous coordination", subTopics: ["CNS and PNS	", "Neuron and peripheral nervous system", "Reflex/Voluntary actions"] },
				{ topic: "Sense organs", subTopics: ["The skin", "Nose/Tongue", "Eye/Ear"] },
				{ topic: "Ecology of population", subTopics: ["Ecological succession/over crowding and food shortage "] },
				{ topic: "Balance in nature", subTopics: ["Family planning and birth control", "Population"] },
				{ topic: "Reproduction in humans", subTopics: ["Viviparity and Oviparity", "Pregnancy and child birth"] },
				{ topic: "Seeds and Fruits", subTopics: ["seeds and germination"] },
				{ topic: "Reproductive behaviour", subTopics: ["Courtship"] },
				{ topic: "Hereditary and genetics", subTopics: ["Mendel/genetics"] },
				{ topic: "Variation and evolution", subTopics: ["Evolution theory and variation in living organisms"] },
				{ topic: "Adaptation for survival", subTopics: ["Competition and succession"] },
				
			],
        },
    },
    {
        subject: "Agricultural Science",
        alias: "Agric",
        id: 6,
        classes: {
            ss1: [
				{ topic: "Problems of agricultural development in Nigeria", subTopics: ["Problems of agricultural development in Nigeria"] },
				{ topic: "Husbandry of selected crops", subTopics: ["Root and tuber e.g Yam, cassava", "Maize/Rice", "Beverage/Latex/Oily crops"] },
				{ topic: "Land and its uses ", subTopics: ["Land"] },
				{ topic: "Anatomy and Physiology", subTopics: ["Terms: Anatomy and Physiology"] },
				{ topic: "System of the body of farm animals", subTopics: ["System of the body of farm animals", "Circulatory and reproductive system of farm animals", "Egg formation"] },
				{ topic: "Livestock management", subTopics: ["Livestock and hornones"] },
				{ topic: "Rock formation", subTopics: ["Type of rocks"] },
				{ topic: "Farm power", subTopics: ["Sources of farm power"] },
				{ topic: "Mechanisation", subTopics: ["Mechanised farms"] },
				{ topic: "Factors of production", subTopics: ["Land/Labor"] },
				{ topic: "Farm management • Agricultural financing", subTopics: ["Farm management • Agricultural financing", "Savings and thrift society", "Farm credits and loans"] },
				
			],
			ss2: [
				{ topic: "Land tenure system", subTopics: ["Land use Acts of 1978"] },
				{ topic: "Governmental roles in agricultural production", subTopics: ["Governmental roles in agricultural production", "Forestry"] },
				{ topic: "Crop Disease", subTopics: ["Major crop diseases"] },
				{ topic: "Pest of crops", subTopics: ["Crop Pest and significance"] },
				{ topic: "Pasture and forage crops", subTopics: ["Nigerian pastures"] },
				{ topic: "Animal nutrition", subTopics: ["Animal nutrition"] },
				{ topic: "Factors affecting agricultural production", subTopics: ["Factors affecting agricultural production", "Environmental/Biotic/Edaphic factors"] },
				{ topic: "Rations and balanced diet", subTopics: ["Rations and balanced diet", "Plant nutrition"] },
				{ topic: "Nutrient cycle", subTopics: ["Water cycle", "Nitrogen cycle", "Carbon cycle"] },
				{ topic: "Effect of farm practice in soil", subTopics: ["Effect of farm practice in soil", "Bush burning", "Over grazing"] },
				{ topic: "Farm machinery", subTopics: ["Farm machinery", "Tractors/Bulldozers/Incubators"] },
				{ topic: "Surveying equipment", subTopics: ["Ranging pole", "Theodolite"] },
				{ topic: "Farm account", subTopics: ["Profit and loss", "Demand and Supply"] },
			],
			ss3: [
				{ topic: "Crop improvement", subTopics: ["Mendel law", "Selection/Breeding"] },
				{ topic: "Principles of animal health management", subTopics: ["Principles of animal health management", "Infection and treatment"] },
				{ topic: "Fish farming", subTopics: ["Fishery"] },
				{ topic: "Irrigation and drainage system", subTopics: ["Irrigation and drainage system"] },
				{ topic: "Agricultural marketing", subTopics: ["Marketing of agricultural produce", "Agricultural extension"] },
				{ topic: "Greek festival and the Olympic games ", subTopics: ["Greek festival and the Olympic games ", "Ancient Olympics games"] },
				{ topic: "International competition • Games", subTopics: ["International competition • Games", "Hockey/Football", "Sport governing bodies"] },
			],
			
        },
    },
    {
        subject: "Geography",
        alias: "Geo",
        id: 7,
        classes: {
            ss1: [
				{ topic: "The solar system • Earth", subTopics: ["Earth's sphericity and rotation", "sun and moon", "Revolution vs Rotation"] },
				{ topic: "Geo climate and vegetation", subTopics: ["Geo climate and vegetation"] },
				{ topic: "Latitude and longitude", subTopics: ["Parallel of latitude"] },
				{ topic: "Rocks", subTopics: ["Rock formation"] },
				{ topic: "Geography of Nigeria", subTopics: ["Location and boundaries", "Nigeria population"] },
				{ topic: "Industries", subTopics: ["Types of industries"] },
				{ topic: "Stages of river development", subTopics: ["Stages of river development"] },
				{ topic: "Action of wind", subTopics: ["Wind and erosion"] },
			],
			ss2: [
				{ topic: "Action of waves", subTopics: ["Even and tide", "Erosion and coastal deposit"] },
				{ topic: "Climatic classification", subTopics: ["Climatic tyoes"] },
				{ topic: "Environmental resources", subTopics: ["Renewable and Non renewable resources"] },
				{ topic: "Environmental hazard/Conservation", subTopics: ["Tourism", "Pollution", "Conservation of natural resources"] },
				{ topic: "Nigeria agriculture • Transportation", subTopics: ["Mechanised/Pastoral agriculture", "Transportation in Nigeria"] },
				{ topic: "Communication in Nigeria", subTopics: ["Forms of communication"] },
				{ topic: "Manufacturing industries in Nigeria", subTopics: ["Manufacturing and commercial activities"] },
				{ topic: "Map reading", subTopics: ["Geographic Map reading"] },
				{ topic: "Relief forms", subTopics: ["Valleys/Plateau/Hill", "Drawing of some relief and colouring"] },
				{ topic: "World population", subTopics: ["Census • World population"] },
				{ topic: "Settlement", subTopics: ["urban and rural settlement"] },
				{ topic: "Geo political issues • Land", subTopics: ["Land Reclamation"] },
				{ topic: "Geographic information system (GIS)", subTopics: ["Satellite and land survey"] },
			],
			ss3: [
				{ topic: "Earthquake and Volcano", subTopics: ["Volcanic eruption"] },
				{ topic: "Denudational process", subTopics: ["Weathering and mass movement"] },
				{ topic: "ECOWAS", subTopics: ["achievements"] },
			],
        },
    },
    {
        subject: "Literature in English",
        alias: "Lit",
        id: 8,
        classes: {
        	"Literary device": [
				{ topic: "Literary Appreciation/Device", subTopics: ["Metonymy/Simile/Metaphor/Hyperbole", "Oxymoron/Paradox/Onomatopoeia"] },
			],
			"Dramatic terms": [
				{ topic: "Dramatic terminologies", subTopics: ["Chrestomathy/Anadiplosis/Hubris/Hermatia", "Settings/Plot/Twist", "Opera/Farce", "Comedy/Tragicomedy/Melodrama"] },
			],
            "Drama": [
				{ topic: "African:  Lion and the Jewel", subTopics: ["Wole Soyinka: Lion and the Jewel"] },
				{ topic: "Non African: Look Back in Anger", subTopics: ["John Osborne: Look Back in Anger"] },
			],
			"Prose": [
				{ topic: "African: Second Class Citizen", subTopics: ["Buchi Emecheta: Second Class Citizen"] },
				{ topic: "African: Unexpected Joy at Dawn", subTopics: ["Alex Agyei Agyiri: Unexpected Joy at Dawn"] },
				{ topic: "Non African: Wuthering Heights", subTopics: ["Emile Bronte: Wuthering Heights"] },
			],
			"Poetry": [
				{ topic: "African: Black Woman", subTopics: ["Leopold Sedar Senghor: Black Woman"] },
				{ topic: "African: The Leader and the Led", subTopics: ["Niyi Osundare: The Leader and the Led"] },
				{ topic: "African: The Grieved Lands", subTopics: ["Agostinho Neto: The Grieved Lands"] },
				{ topic: "African: The Song of the Women of the lands", subTopics: ["Oumar Farouk Sesay: The Song of the Women of the lands"] },
				{ topic: "African: Raider of the Treasure Trove", subTopics: ["Lade Wosornu: Raider of the Treasure Trove"] },
				{ topic: "African: A Government Driver on his Retirement", subTopics: ["Onu Chibuike: A Government Driver on his Retirement"] },
				{ topic: "Non-African: The Good Morrow", subTopics: ["John Donne: The Good Morrow"] },
				{ topic: "Non-African: Caged Birds", subTopics: ["Maya Angelou: Caged Birds"] },
				{ topic: "Non-African: The Journey of the Magi", subTopics: ["T. S. Elliot: The Journey of the Magi"] },
				{ topic: "Non-African: Bats", subTopics: ["D. H. Lawrence:  Bats"] },
				
			],


        },
    },
    {
        subject: "Government",
        alias: "Govt",
        id: 9,
        classes: {
            ss1: [
				{ topic: "Basic concept of Government", subTopics: ["communalism/socialism/capitalism", "Feudalism/oligarchy/totalitarianism", "Democracy/sovereignty", "legitimacy and authority"] },
				{ topic: "Types and characteristics of government", subTopics: ["Characteristics of Government", "Military rule/Presidency", "Monarchy/Confederal Government", "Parliament and Republican"] },
				{ topic: "Constitution", subTopics: ["Constitution and types"] },
				{ topic: "Structure and organisations of government", subTopics: ["Structure and organisations of government", "Executive/Legislative and Judiciary", "Bills"] },
				{ topic: "Basic principles of government", subTopics: ["Rule of law/Fundamental human right", "Liberty/Constitutionalism", "Power/Centralisation/Decentralisation", "Delegated legislation"] },
				{ topic: "Citizenship", subTopics: ["Rights of citizens", "Civil society"] },
				{ topic: "Political parties and Party System", subTopics: ["structure of political party", "Multi-party system"] },
				{ topic: "Pressure Groups", subTopics: ["pressure groups"] },
			],
			ss2: [
				{ topic: "Franchise", subTopics: ["Suffrage and Franchise"] },
				{ topic: "Electoral system/Election", subTopics: ["Election and Electrical malpractice"] },
				{ topic: "Public Opinion", subTopics: ["Public Opinion"] },
				{ topic: "Mass media", subTopics: ["Roles of mass Media"] },
				{ topic: "Public administration", subTopics: ["Civil services/Police", "Public operations/Privatisation/Commercialisation/Deregulation", "Local government"] },
				{ topic: "Pre-colonial political system", subTopics: ["Igbo/Hausa/Yoruba"] },
				{ topic: "Colonial administration", subTopics: ["Indirect rule/Policy if assimilation", "British and French Colonial system"] },
				{ topic: "Nationalism", subTopics: ["Africanist and Nationalism"] },
				{ topic: "Pre-independence constitution", subTopics: ["Clifford/MacPherson/Richard/Lyttleton constitution"] },
				{ topic: "Post-independence constitution and Republican", subTopics: ["Independence constitution", "Republican"] },
			],
			ss3: [
				{ topic: "Nigerian federalism", subTopics: ["federalism"] },
				{ topic: "Creation of state", subTopics: ["State creation in Nigeria"] },
				{ topic: "Development of political parties", subTopics: ["Political parties in Nigeria", "Crises in politics"] },
				{ topic: "Military rule", subTopics: ["Nigerian military rule"] },
				{ topic: "Conflict resolution and management", subTopics: ["Conflict and Peace education"] },
				{ topic: "Foreign Policy", subTopics: ["Foreign Policy"] },
				{ topic: "International Organisations", subTopics: ["ECOWAS/OPEC", "OAU/AU/NEPAD", "Common wealth and League of Nations", "United Nations (UN)"] },
			],
			
        },
    },
    {
        subject: "Economics",
        alias: "Econs",
        id: 10,
        classes: {
            ss1: [
				{ topic: "Introduction to Economics", subTopics: ["Scale of preference/Opportunity cost", "Want/Scarcity and choice"] },
				{ topic: "Basic Economic Analysis tools", subTopics: ["Pie-chart/Bar chart and graph", "Mean/Median/Mode"] },
				{ topic: "Concept of Demand and Supply", subTopics: ["Demand and Equilibrium of price"] },
				{ topic: "Theory of production", subTopics: ["Factors of production", "Entrepreneurship"] },
				{ topic: "Division of labour", subTopics: ["Small and large firms"] },
				{ topic: "Basic Economic problems", subTopics: ["How/What to produce"] },
				{ topic: "Business organisations", subTopics: ["Business organisations", "Partnership and sole proprietorship", "Limited Liability companies", "Public cooperation and cooperative society", "Stock/Shares and Debentures"] },
				{ topic: "Population", subTopics: ["Census"] },
				{ topic: "Labour Market", subTopics: ["Mobility of labour"] },
				{ topic: "Nature of Nigerian economy", subTopics: ["Economic potential"] },
				{ topic: "Agriculture/Mining", subTopics: ["Agricultural services and mining"] },
				{ topic: "Financial institution", subTopics: ["Banks/Cheques", "Money/Capital market and stock exchange market"] },
				{ topic: "Money", subTopics: ["Money and trade by barter"] },
				{ topic: "Channels of distribution", subTopics: ["Wholesalers/Retailers and Middlemen"] },
				{ topic: "Instruments of business finance", subTopics: ["Stock/Debentures/Shares"] },
			],
			ss2: [
				{ topic: "Basic tools for Economic Analysis", subTopics: ["Variance and standard deviation", "Range/Quartile", "Measures of Dispersion"] },
				{ topic: "Demand and Supply", subTopics: ["Laws of demand and supply"] },
				{ topic: "Production possibility curve", subTopics: ["Opportunity cost and Marginal product", "Law of variable proportion"] },
				{ topic: "Cost concepts", subTopics: ["Average marginal cost"] },
				{ topic: "Revenue concepts", subTopics: ["Revenue and profit"] },
				{ topic: "Types and features of economic system", subTopics: ["Capitalism and socialism"] },
				{ topic: "Labour Market", subTopics: ["Supply of labour", "Job creation", "Wages and Labour"] },
				{ topic: "Elementary treatment of utility Theory", subTopics: ["Average utility"] },
				{ topic: "Price determination", subTopics: ["Concept of supply and demand"] },
				{ topic: "Market structures", subTopics: ["Monopoly/Market"] },
				{ topic: "Industries in Nigeria", subTopics: ["Industrie in Nigeria"] },
				{ topic: "Fiscal Policy", subTopics: ["Government expenditure and Tax"] },
				{ topic: "Balanced and Unbalanced budget", subTopics: ["Surplus deficit budget"] },
				{ topic: "Elements of National income accounting", subTopics: ["Cost of living"] },
				{ topic: "Financial institution and their function", subTopics: ["Money market"] },
				{ topic: "Demand and Supply of Money", subTopics: ["Value of Money"] },
				{ topic: "Inflation and Deflation", subTopics: ["inflation/Deflation"] },
			],
			ss3: [
				{ topic: "Economic lessons from Asian Tigers, Japan, Europe and America", subTopics: ["Economic lessons from Asian Tigers, Japan, Europe and America", "History and Japanese miracle"] },
				{ topic: "Human capital development", subTopics: ["Brain drain"] },
				{ topic: "Petroleum and Nigerian economy", subTopics: ["NNPC"] },
				{ topic: "Manufacturing and Construction", subTopics: ["Nigerian industries"] },
				{ topic: "Service industries", subTopics: ["Service occupation"] },
				{ topic: "Regulatory agencies of Financial institution", subTopics: ["Regulatory agencies of Financial institution", "CBN", "NDIC/SEC"] },
				{ topic: "International trade", subTopics: ["trade/international trade"] },
				{ topic: "Balance of payment (B.O.P)", subTopics: ["Balance o payment disequilibrium"] },
				{ topic: "Economic growth and development", subTopics: ["Economic growth", "Economic planning"] },
				{ topic: "International Economic Organisation", subTopics: ["ECOWAS/ECA"] },
				{ topic: "Elementary Theory of Income determination", subTopics: ["Elementary Theory of Income determination", "Concept of investment", "Economic challenges", "Economic reform programmes"] },
			],
        },
    },
    {
        subject: "History",
        alias: "Hist",
        id: 11,
        classes: {
            ss1: [
				{ topic: "Historical skills • Ancient/Modern", subTopics: ["Cultural artifacts", "Prospect for ICT in historical studies"] },
				{ topic: "Land and People of Nigeria", subTopics: ["Coastal/Forestry and Semi Savannah region", "Rivers/Mountain", "Culture"] },
				{ topic: "Early centers of civilisation in Nigeria", subTopics: ["Early centers of civilisation in Nigeria", "Benin/Igbo Ukwu/Ife"] },
				{ topic: "State formation process", subTopics: ["Kanem/Bornu - NOK", "Efik/Igala", "Igbo/Isobo/Ibibio"] },
				{ topic: "The Hausa states to 1800", subTopics: ["Evolution", "Jihad war"] },
				{ topic: "Nupe/Jukun empire", subTopics: ["Perculiar information"] },
				{ topic: "Ile Ife and Oyo empire", subTopics: ["Yoruba origin"] },
				{ topic: "Benin empire", subTopics: ["Benin Kingdom Origin"] },
				{ topic: "The Efik", subTopics: ["History"] },
				{ topic: "Inter group relations", subTopics: ["Wars and Politics of ethnic groups e.g Benin/Efik"] },
				{ topic: "Early external influence", subTopics: ["Contact with the North", "Islam in Kanem/Bornu"] },
				{ topic: "European Contact", subTopics: ["Early European Contact"] },
				{ topic: "Trans Atlantic slave trade", subTopics: ["Slave trade"] },
				
			],
			ss2: [
				{ topic: "Jihad war • The Sokoto caliphate", subTopics: ["Jihad war/The Sokoto caliphate"] },
				{ topic: "Bornu • Under The Shehus", subTopics: ["Rebellion and crisis"] },
				{ topic: "Yoruba land in the 19th century", subTopics: ["Final collapse of Oyo empire"] },
				{ topic: "First phase of British conquest • 1851 - 1900/1990 - 1914", subTopics: ["First phase of British conquest • 1851 - 1900/1990 - 1914", "Occupation of Igbo/North Sokoto"] },
				{ topic: "Amalgamation of Nigeria and its significance", subTopics: ["Amalgamation"] },
				{ topic: "Colonial Rule/Economy", subTopics: ["Nature of indirect rule", "British policy of the Economy and the effect"] },
				{ topic: "Origin of Nationalism", subTopics: ["Jaja of Opobo", "Awujale of Ijebuode", "Ovonrenewem of Benin"] },
				{ topic: "Decolonisation", subTopics: ["Decolonisation"] },
				{ topic: "First Republic • 1960-1996", subTopics: ["First Republic • 1960-1996"] },
				{ topic: "Nigeria Civil war • 1966 Coup detat", subTopics: ["Nigeria Civil war • 1966 Coup detat"] },
				{ topic: "Military rule • Reconstruction in Nigeria", subTopics: ["Military rule • Reconstruction in Nigeria", "Yakubu Gowon regume"] },
				{ topic: "Second Republican • 1979", subTopics: ["Adoption of bicameralism and multiparty democracy"] },
				{ topic: "Return of the military rule in 1983", subTopics: ["Return of the military rule in 1983"] },
				{ topic: "Ibrahim Babaginda Regime • 1985 - 1993", subTopics: ["Ibrahim Babaginda Regime • 1985 - 1993"] },
				{ topic: "Transition • Fourth Republican", subTopics: ["Transition • Fourth Republican"] },
			],
			ss3: [
				{ topic: "Islamic movement in West Africa", subTopics: ["Spread of islam"] },
				{ topic: "The Jihad of Seku Ahmadu", subTopics: ["Theocratic state"] },
				{ topic: "The Jihad of Alhaji Umar", subTopics: ["The Tukuer people"] },
				{ topic: "The activities of Samori-Toure", subTopics: ["The Mandika empire"] },
				{ topic: "Berlin conference", subTopics: ["Colonial subjugation"] },
			],
        },
    },
    {
        subject: "Christian Religious Studies",
        alias: "CRS",
        id: 12,
        classes: {
            ss1: [
				{ topic: "", subTopics: [""] },
			],
			ss2: [
				{ topic: "", subTopics: [""] },
				{ topic: "", subTopics: [""] },
			],
			ss3: [
				{ topic: "", subTopics: [""] },
			],
        },
    },
    {
        subject: "Islamic Religious Studies",
        alias: "IRS",
        id: 13,
        classes: {
            ss1: [
				{ topic: "", subTopics: [""] },
			],
			ss2: [
				{ topic: "", subTopics: [""] },
			],
			ss3: [
				{ topic: "", subTopics: [""] },
			],
        },
    },
    {
        subject: "Financial Accounting",
        alias: "Acct",
        id: 14,
        classes: {
            ss1: [
				{ topic: "Book keeping and accounting", subTopics: ["Stock valuation", "Ethics of accounting"] },
				{ topic: "Principles • Double entry", subTopics: ["Rules of double entry", "Double column cash book"] },
				{ topic: "Analytical Cash book", subTopics: ["Petty cash book"] },
				{ topic: "Subsidiary Book • Source documents", subTopics: ["Subsidiary Book and Source documents"] },
				{ topic: "Trial balance", subTopics: ["Formation layout"] },
				
			],
			ss2: [
				{ topic: "Journal", subTopics: ["General Journal", "Opening and closing entries"] },
				{ topic: "Correction of errors", subTopics: ["Accounting errors", "Preparation and error correction"] },
				{ topic: "Suspense Account", subTopics: ["Preparation of suspense account"] },
				{ topic: "Classification of accounts", subTopics: ["Personal/Impersonal/Real and nominal account"] },
				{ topic: "Bank reconciliation statement", subTopics: ["Terminologies", "Preparation of Bank reconciliation statement"] },
				{ topic: "Accounting Concepts", subTopics: ["Entity Concept"] },
				{ topic: "Trading account", subTopics: ["Preparation of trading account"] },
				{ topic: "Trading • Profit and loss account", subTopics: ["Trading/Profit and loss account", "Determination of Net profit/loss"] },
				
			],
			ss3: [
				{ topic: "Purchase of business account", subTopics: ["Purchase of business account", "Vendors account"] },
				{ topic: "Hire Purchase and instalment payment account", subTopics: ["Hire Purchase and instalment payment account", "Vendors book"] },
				{ topic: "Consignment account", subTopics: ["Account preparation"] },
				{ topic: "Joint ventures account", subTopics: ["Partnership and joint venture"] },
				{ topic: "Departmental account", subTopics: ["Departmental account"] },
				{ topic: "Branch account", subTopics: ["Branch account"] },
			],
        },
    },
    {
        subject: "Commerce",
        alias: "Com",
        id: 15,
        classes: {
            ss1: [
				{ topic: "Commerce and History of commerce", subTopics: ["The barter system", "E-Commerce"] },
				{ topic: "Occupation", subTopics: ["Service occupation"] },
				{ topic: "Production", subTopics: ["Factors of production"] },
				{ topic: "Trade", subTopics: ["Meaning and type of trade"] },
				{ topic: "Small/Large scale retail", subTopics: ["Supermarket"] },
				{ topic: "Wholesale Trade and Middle men", subTopics: ["Wholesale Trade and Middle men", "Merchant/Wholesalers"] },
				{ topic: "Partnership", subTopics: ["Partnership and dissolution"] },
				{ topic: "Commodity exchange", subTopics: ["Benefit of commodity exchange"] },
				{ topic: "Documents used in foreign Trade", subTopics: ["Documents used in foreign Trade", "Mail transfer"] },
				{ topic: "Balance of trade and balance of payment", subTopics: ["Balance of trade and balance of payment", "Tariffs and restrictions of foreign trade"] },
				{ topic: "Transportation", subTopics: ["Transport system"] },
				{ topic: "Money", subTopics: ["Money system"] },
				{ topic: "Trade association and other enterprises", subTopics: ["Trade association and other enterprises", "Aims and functions"] },
				{ topic: "Limited Liability companies", subTopics: ["Shares/Debentures", "Liquidation and dissolution of LLC"] },
				{ topic: "Public enterprises", subTopics: ["Public enterprises"] },
				{ topic: "Cooperative society", subTopics: ["advantages and disadvantages"] },
			],
			ss2: [
				{ topic: "Communications", subTopics: ["Modern/Traditional means of communication", "Email"] },
				{ topic: "Advertisement", subTopics: ["Types of advertisement", "Social Media"] },
				{ topic: "Tourism", subTopics: ["Obudu cattle Ranch and Park tourist attractions"] },
				{ topic: "Insurance", subTopics: ["Insurance and type of insurance"] },
				{ topic: "Banking", subTopics: ["Types of bank account", "Types of bank", "Central bank"] },
				{ topic: "Payment system", subTopics: ["E-banking", "Cheque"] },
				{ topic: "Warehousing", subTopics: ["advantage/disadvantages of warehousing"] },
				{ topic: "Capital", subTopics: ["Working capital"] },
				{ topic: "Credit", subTopics: ["Hire purchase"] },
				{ topic: "Profit", subTopics: ["Net profit"] },
				{ topic: "Turnover", subTopics: ["Turnover"] },
				{ topic: "Business law", subTopics: ["Contract law", "Misrepresentation mistake"] },
				{ topic: "Principles of agency", subTopics: ["Intellectual property"] },
				{ topic: "Business structure", subTopics: ["Intra departmental"] },
				{ topic: "Introduction to Business Management", subTopics: ["Goodwill"] },
				{ topic: "Business Organisation", subTopics: ["Departmentalisation"] },
				{ topic: "Introduction to Marketing", subTopics: ["Price mix", "Methods of promotion"] },
			],
			ss3: [
				{ topic: "Consumer protection", subTopics: ["Professional bodies involved"] },
				{ topic: "Business documents", subTopics: ["Essential Business documents"] },
				{ topic: "Terms of trade/sale ", subTopics: ["Terminologies of trade/sale"] },
				{ topic: "Commercialisation", subTopics: ["Privatisation and deregulation"] },
				{ topic: "Capital market", subTopics: ["Capital market"] },
				{ topic: "Stock exchange • Economic grouping", subTopics: ["Stock exchange • Economic grouping", "Nigerian Basin commission"] },
			],
        },
    },
    {
        subject: "Fine Art",
        alias: "Art",
        id: 16,
        classes: {
            ss1: [
				{ topic: "", subTopics: [""] },
			],
			ss2: [
				{ topic: "", subTopics: [""] },
			],
			ss3: [
				{ topic: "", subTopics: [""] },
			],
        },
    },
    {
        subject: "French",
        id: 17,
        alias: "FRE",
        classes: {
            ss1: [
				{ topic: "", subTopics: [""] },
			],
			ss2: [
				{ topic: "", subTopics: [""] },
			],
			ss3: [
				{ topic: "", subTopics: [""] },
			],
        },
    },
    {
        subject: "Music",
        alias: "MSC",
        id: 18,
        classes: {
            ss1: [
				{ topic: "", subTopics: [""] },
			],
			ss2: [
				{ topic: "", subTopics: [""] },
			],
			ss3: [
				{ topic: "", subTopics: [""] },
			],
        },
    },
    {
        subject: "Physical Education",
        alias: "PEDU",
        id: 19,
        classes: {
            ss1: [
				{ topic: "", subTopics: [""] },
			],
			ss2: [
				{ topic: "", subTopics: [""] },
			],
			ss3: [
				{ topic: "", subTopics: [""] },
			],
        },
    },
];
